# Generated by Django 2.1.5 on 2019-01-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='edited_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
