# Generated by Django 2.1.5 on 2019-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20190109_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
