# Generated by Django 2.1.5 on 2019-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_artwork_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
