# Generated by Django 2.1.5 on 2019-01-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_auto_20190109_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='origin_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
