# Generated by Django 2.1.5 on 2019-01-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_artwork_origin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='origin_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
