# Generated by Django 2.1.5 on 2019-01-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_auto_20190125_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='url_local',
            field=models.ImageField(blank=True, default='', upload_to='artworks'),
        ),
    ]
