# Generated by Django 2.1.5 on 2019-01-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_artwork_url_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='url_online',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
