# Generated by Django 2.1.5 on 2019-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_auto_20190125_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='date_display',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
