# Generated by Django 2.1.5 on 2020-06-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_auto_20190129_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('edited_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='origin_id',
            new_name='origin_artwork_id',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Origin'),
        ),
    ]
