# Generated by Django 2.1.5 on 2020-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_auto_20200607_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('edited_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('alpha2', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
            ],
        ),
    ]
