# Generated by Django 2.1.5 on 2020-06-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='artwork',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='museum.Country'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='museum.Origin'),
        ),
    ]
