# Generated by Django 2.1.5 on 2020-06-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0014_auto_20200607_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='country',
            new_name='author_country',
        ),
    ]
