# Generated by Django 2.1.5 on 2020-08-08 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0017_auto_20200808_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='pseudo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='scoreA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='scoreB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GameUser',
        ),
    ]
