# Generated by Django 2.1.5 on 2020-08-08 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0018_auto_20200808_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='game',
            name='usersA',
            field=models.ManyToManyField(related_name='gameA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='usersB',
            field=models.ManyToManyField(related_name='gameB', to=settings.AUTH_USER_MODEL),
        ),
    ]
