# Generated by Django 3.1 on 2020-12-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0019_auto_20200808_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevent',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameEvent',
        ),
    ]
